version: '3.8'

services:

  backend-1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
      NODE_ID: node-1
      NODE_ADDRESS: backend-1
      NODE_PORT: 8000
      API_PORT: 8000
      VIRTUAL_NODES: 150
      REPLICATION_FACTOR: 2
      UPLOAD_DIR: /app/music_files
      RAFT_DATA_DIR: /app/raft_data
      BOOTSTRAP_SERVICE: "dispotify-cluster"
    volumes:
      - ./backend/app:/app/app
      - ./music_files_node1:/app/music_files
      - ./raft_data_node1:/app/raft_data
    ports:
      - "8001:8000"
    networks:
      dispotify-network:
        aliases:
          - dispotify-cluster
    restart: unless-stopped

  backend-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: your-secret-key-change-in-production
      ENVIRONMENT: development
      NODE_ID: node-2
      NODE_ADDRESS: backend-2
      NODE_PORT: 8000
      API_PORT: 8000
      VIRTUAL_NODES: 150
      REPLICATION_FACTOR: 2
      UPLOAD_DIR: /app/music_files
      RAFT_DATA_DIR: /app/raft_data
      BOOTSTRAP_SERVICE: "dispotify-cluster"
    volumes:
      - ./backend/app:/app/app
      - ./music_files_node2:/app/music_files
      - ./raft_data_node2:/app/raft_data
    ports:
      - "8002:8000"
    networks:
      dispotify-network:
        aliases:
          - dispotify-cluster
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8001/
    ports:
      - "3000:3000"
    depends_on:
      - backend-1
      - backend-2
    networks:
      - dispotify-network
    restart: unless-stopped

networks:
  dispotify-network:
    driver: overlay  # Para simular Docker Swarm
