version: '3.8'

services:

  # Base de datos
  db:
    image: postgres:15-alpine
    container_name: dispotify_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dispotify
    networks:
      - dispotify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dispotify"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Nodo API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dispotify-api:latest
    container_name: dispotify_api
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/dispotify
      NODE_ID: node-1
      NODE_ADDRESS: api
      NODE_PORT: 8000
      VIRTUAL_NODES: 150
      REPLICATION_FACTOR: 1
      UPLOAD_DIR: /app/music_files
      RAFT_DATA_DIR: /app/raft_data
      RAFT_ELECTION_TIMEOUT_MIN: "0.15"
      RAFT_ELECTION_TIMEOUT_MAX: "0.30"
      RAFT_HEARTBEAT_INTERVAL: "0.1"
      SOLO_MODE_TIMEOUT: "15.0"
      PYTHONUNBUFFERED: 1
    networks:
      - dispotify-network
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://127.0.0.1:8000/api/v1/
    image: dispotify-frontend:latest
    container_name: dispotify_frontend
    environment:
      VITE_API_URL: http://127.0.0.1:8000/api/v1/
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - dispotify-network
    restart: unless-stopped

networks:
  dispotify-network:
    driver: bridge

